# Generated by Django 5.2 on 2026-01-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2, default=10000000.0, max_digits=15
                    ),
                ),
            ],
        ),
    ]
